---
all:
  hosts:
    sonar-01:
      ansible_host: 51.250.115.29
    nexus-01:
      ansible_host: 51.250.113.75
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vitas